# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_pretty = QtWidgets.QWidget()
        self.tab_pretty.setObjectName("tab_pretty")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_pretty)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_pretty)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_pretty_filling_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_pretty_filling_2.setObjectName("comboBox_pretty_filling_2")
        self.gridLayout.addWidget(self.comboBox_pretty_filling_2, 1, 3, 1, 1)
        self.comboBox_pretty_filling = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_pretty_filling.setObjectName("comboBox_pretty_filling")
        self.gridLayout.addWidget(self.comboBox_pretty_filling, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.checkBox_pretty_right = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pretty_right.setObjectName("checkBox_pretty_right")
        self.gridLayout.addWidget(self.checkBox_pretty_right, 0, 0, 1, 2)
        self.checkBox_pretty_link = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pretty_link.setObjectName("checkBox_pretty_link")
        self.gridLayout.addWidget(self.checkBox_pretty_link, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_pretty)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_pretty_comment = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pretty_comment.setObjectName("lineEdit_pretty_comment")
        self.gridLayout_2.addWidget(self.lineEdit_pretty_comment, 0, 1, 1, 1)
        self.checkBox_pretty_capitalize = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_pretty_capitalize.setObjectName("checkBox_pretty_capitalize")
        self.gridLayout_2.addWidget(self.checkBox_pretty_capitalize, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalSlider_pretty_ncols = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_pretty_ncols.setMinimum(10)
        self.horizontalSlider_pretty_ncols.setMaximum(100)
        self.horizontalSlider_pretty_ncols.setSingleStep(10)
        self.horizontalSlider_pretty_ncols.setProperty("value", 50)
        self.horizontalSlider_pretty_ncols.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pretty_ncols.setTickInterval(10)
        self.horizontalSlider_pretty_ncols.setObjectName("horizontalSlider_pretty_ncols")
        self.gridLayout_2.addWidget(self.horizontalSlider_pretty_ncols, 1, 1, 1, 1)
        self.label_pretty_ncols = QtWidgets.QLabel(self.groupBox_2)
        self.label_pretty_ncols.setText("")
        self.label_pretty_ncols.setObjectName("label_pretty_ncols")
        self.gridLayout_2.addWidget(self.label_pretty_ncols, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_pretty)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_pretty_load_text = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_pretty_load_text.setObjectName("pushButton_pretty_load_text")
        self.gridLayout_3.addWidget(self.pushButton_pretty_load_text, 0, 0, 1, 1)
        self.pushButton_pretty_options_file = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_pretty_options_file.setObjectName("pushButton_pretty_options_file")
        self.gridLayout_3.addWidget(self.pushButton_pretty_options_file, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_pretty, "")
        self.tab_regexp = QtWidgets.QWidget()
        self.tab_regexp.setObjectName("tab_regexp")
        self.tabWidget.addTab(self.tab_regexp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_copy_textEdit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy_textEdit.setObjectName("pushButton_copy_textEdit")
        self.horizontalLayout.addWidget(self.pushButton_copy_textEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Comment style"))
        self.label.setText(_translate("MainWindow", "Filling character: "))
        self.checkBox_pretty_right.setText(_translate("MainWindow", "Add right-hand side comment character"))
        self.checkBox_pretty_link.setText(_translate("MainWindow", "Link"))
        self.label_2.setText(_translate("MainWindow", "Filling character 2: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Contents"))
        self.label_4.setText(_translate("MainWindow", "Create comment block:"))
        self.lineEdit_pretty_comment.setPlaceholderText(_translate("MainWindow", "Block name..."))
        self.checkBox_pretty_capitalize.setText(_translate("MainWindow", "Capitalize"))
        self.label_5.setText(_translate("MainWindow", "Number of columns: "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tools"))
        self.pushButton_pretty_load_text.setText(_translate("MainWindow", "Load options from text"))
        self.pushButton_pretty_options_file.setText(_translate("MainWindow", "Load options from file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pretty), _translate("MainWindow", "Pretty code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_regexp), _translate("MainWindow", "Regexp"))
        self.pushButton_copy_textEdit.setText(_translate("MainWindow", "Copy to clipboard"))

